### ISSUE TITLE
Temperature very wrong

### ISSUE THREAD

**Issue by NeuerUser** [smartboxchannel/Plant-Watering-Sensor-Zigbee#10]
I just got two Plant Watering Sensor EFEKTA (Zigbee) from tindie. Both show about 7 °C to low temperature (e.g. 14°C instead of 21°C). Is this normal or a defect? I have never experienced such a big difference.

And one question: Can the sensor be used outdoor in the garden? I bought it with enclosure, but I do not know, if it is water resistant enough for an outdoor usage.

Thanks!

**Comment by NeuerUser** [comment]
Just saw there is a closed issue about temnperature: https://github.com/smartboxchannel/Plant-Watering-Sensor-Zigbee/issues/8
Is it the same? If yes, then it is clear.
Btw, the temperature seems to work, even though it is 7°C too low. It can be adjusted in z2m and gives a nice temperature indication. I would prefer to keep it reported.

Which leaves the question about using the sensor outdoors. I hope that is possible as this is my only use case.

**Comment by smartboxchannel** [comment]
A protective cap is required to use the sensor outdoors. As for the chip temperature, I wrote somewhere that this parameter will be removed from the z2m converter for this particular version of the sensor, as it raises too many questions. If the air temperature is needed, it will be necessary to use other versions of sensors with digital temperature sensors.
