### ISSUE TITLE
Add a temperature and humidity combo sensor (AM2302, Si7021, DHT11 or DHT22)

### ISSUE THREAD

**Issue by Hedda** [smartboxchannel/Plant-Watering-Sensor-Zigbee#4]
Request add a temperature and humidity combination sensor to the hardware design and firmware.

Examples of an Arduino compatible temperature and humidity sensors are  AM2302, Si7021, DHT11, DHT21, or DHT22

**Comment by smartboxchannel** [comment]
coming soon :)

**Comment by smartboxchannel** [comment]
Added SHTC3, others are not planned
