### ISSUE TITLE
Device only publishing announce messages, no sensor payloads

### ISSUE THREAD

**Issue by djfluffkins** [smartboxchannel/Plant-Watering-Sensor-Zigbee#7]
Hi, I bought 3 of these a while back. I had them set up for almost 3 weeks and it was doing fine (the reporting frequencies were not consistent). 

The battery ran out so I replaced them and all of a sudden the devices would only publish announce messages to zigbee2MQTT never a payload.

```
MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Money Tree Sensor","ieee_address":"0x00124b000611c77e"},"type":"device_announce"}'

MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Money Tree Sensor"},"type":"device_announced"}'

```
I replaced all three and it seems to still have issues.
I've tried resetting to factory defaults (hold button for 10 seconds) and then force remove and readding them to my setup.

They sometimes take a while to trigger the interview but they are connected fine and the only t hing they'll publish is the LQI. 

Not sure what I can do to fix this. 

Also was it ever configured that pushing the button once would send the active payload?

**Comment by smartboxchannel** [comment]
Hello, you probably need to re-add devices to the network. To do this, first remove them through the force remove function and then add them again. In general, it looks like an incomplete interview. Sending data by short-term pressing of the button has always been, just click on it briefly

**Comment by cowana** [comment]
@djfluffkins, did this fix work for you? I am having the same issue with multiple sensors (they appear to interview fine and appear in Z2M, but never transmit any sensor data).

If you found an alternative fix I would be very interested to hear it!
